### PR TITLE
linux: add floorp browser

### PR DESCRIPTION
**Pull request by pricci1**
Add the linux variant of the [Floorp](https://github.com/Floorp-Projects/Floorp/) browser (Firefox based)

### CODE REVIEW

**Comment by liias** [comment]
Hi Pedro, thanks for the contribution!

This .toml file is only for giving special support for profiles (so in this case floorp profiles). In order to do that, it's also mandatory to specify `config_dir_relative`. Could you open `about:profiles` in Floorp and check the value of any the Root Directory of any profile, e.g I have for firefox: `/home/user/.mozilla/firefox/onkvhqmt.default-esr` in which case `config_dir_relative` is `.mozilla/firefox`.

Another part - the `id` must match the `.desktop` file name for floorp (usually `.desktop` files are under `/usr/share/applications/`). If the filename there is `floorp.desktop` then the `id` should be the same, but without `.desktop` extension, so `floorp`

**Comment by pricci1** [comment]
You mentioned "profiles/containers". I do have the "Multi-Accounts containers" extension installed in both Firefox and Floopr.

How can I check if they are working with `browsers`? I didn't even realize they where supported

**Comment by liias** [comment]
Awesome, thanks for the updates and good words!

Merging it to `main`, but I'm not creating a new release very soon (as there's some unrelated end-to-end test issue with Windows right now)

**Comment by liias** [comment]
> You mentioned "profiles/containers". I do have the "Multi-Accounts containers" extension installed in both Firefox and Floopr.
> 
> How can I check if they are working with `browsers`? I didn't even realize they where supported

You need this odd extension https://addons.mozilla.org/en-US/firefox/addon/open-url-in-container/ right now until (if ever) https://bugzilla.mozilla.org/show_bug.cgi?id=1726634 is resolved

**Comment by pricci1** [comment]
Nice. I can confirm containers are showing up with that extension (your fork) installed in Floorp

**Pull request merged**
